apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mongodb
        tier: db
    app: mongodb
    spec:
      containers:
        - image: products-review/mongodb
          name: mongo
          ports:
            - name: http
              containerPort: 27017
              protocol: TCP
          resources:
            {}
          volumeMounts:
            - mountPath: /data/db
              name: mongo-db-data
          lifecycle:
            postStart:
              exec:
                command: ["/bin/bash", "-c", "/docker-entrypoint-initdb.d/init-db.sh", "&&", "exit $?"]
      restartPolicy: Always
      volumes:
        - name: mongo-db-data
          persistentVolumeClaim:
            claimName: mongo-db-data
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
    - name: mongodb-port
      protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mongodb
  name: mongo-db-data
spec:
  storageClassName: manual
  volumeName: mongodb-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/mongo"
  