name: ci
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: yokawasa/action-setup-kube-tools@v0.11.1
      with:
        setup-tools: |
          kubectl
          helm
          kustomize
          skaffold
          rancher
          tilt
        tilt: 0.33.17
    - run: |
      kubectl version --client
      kustomize version
      helm version
      rancher --version
      tilt version
      skaffold version
      tilt ci
