name: ci
on:
  push: { branches: [ main ] }
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: yokawasa/action-setup-kube-tools@v0.11.1
      with:
        tilt: 0.33.17
    - run: |
        kubectl version --client
        kustomize version
        helm version
        rancher --version
        tilt version
        skaffold version
    - run: wget -q -O - https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash
    - run: ./k3d-with-registry.sh
    - run: tilt ci
